CREATE TABLE ORDERS(ID BIGINT auto_increment primary key, INSTRUMENT_ID BIGINT,QUANTITY BIGINT,ENTRY_TIMESTAMP TIMESTAMP,ORDER_TYPE TINYINT,STATUS TINYINT,ASK_PRICE DECIMAL,EXECUTED_QUANTITY BIGINT,EXECUTED_PRICE DECIMAL);
                
CREATE TABLE EXECUTIONS(ID BIGINT auto_increment primary key, INSTRUMENT_ID BIGINT, QUANTITY BIGINT,PRICE DECIMAL);
                
CREATE TABLE INSTRUMENTS(ID BIGINT auto_increment primary key,SYMBOL VARCHAR(20));
 
CREATE TABLE ORDERBOOK(INSTRUMENT_ID BIGINT primary key,BOOK_STATUS TINYINT);
                
insert into INSTRUMENTS(SYMBOL) values('IBM.N');
insert into INSTRUMENTS(SYMBOL) values('UBER.N');
insert into INSTRUMENTS(SYMBOL) values('APPL.N');